### ISSUE TITLE
Kline interval not present in web-socket response for candles_subscribe method

### ISSUE THREAD

**Issue by 5oni** [whitebit-exchange/api-docs#4]
I am using [https://whitebit-exchange.github.io/api-docs/public/websocket/#kline](https://whitebit-exchange.github.io/api-docs/public/websocket/#kline) method to subscribe multiple interval Klines but response does not return kline interval. So i am not able to differentiate the candle response. Also  **id** field is **null** in every response.
      
![image](https://user-images.githubusercontent.com/75757260/226847645-6d495db6-d460-4b8e-8abe-22384c0cdcc4.png)

**Comment by john-whitebit** [comment]
Hello 5oni!

It appears that you are receiving update messages for your subscription request, rather than responses. You can find the documentation for the subscribe method here: https://whitebit-exchange.github.io/api-docs/public/websocket/#subscribe.

The "id" property in all update messages will be null because it is used to identify responses to specific requests. However, update messages are not considered responses, so the "id" field remains null.

Regarding the differentiation of candle responses based on kline intervals, you will need to keep track of the intervals you used to subscribe to the klines. This is because the interval is fixed upon subscription and does not change, so it is not included in the update messages. To handle this, maintain a record of the intervals you've subscribed to and associate them with the respective candle responses you receive.

**Comment by 5oni** [comment]
I didn't get it. let's assume i subsribed 60 seconds,120 seconds and 300 seconds on a single web socket connection. Now I am receiving these responses on a single message channel one by one. 
`{
  method: 'candles_update',
  params: [
    [
      1679443200,
      '28102.42',
      '28257.49',
      '28283.42',
      '27947.17',
      '2109.370014',
      '59290959.89563356',
      'BTC_USDT'
    ]
  ],
  id: null
} 
`,
`{
  method: 'candles_update',
  params: [
    [
      1679443200,
      '28102.42',
      '28257.49',
      '28283.42',
      '27947.17',
      '2109.489565',
      '59294338.10682055',
      'BTC_USDT'
    ]
  ],
  id: null
} `,
`{
  method: 'candles_update',
  params: [
    [
      1679443200,
      '28102.42',
      '28257.49',
      '28283.42',
      '27947.17',
      '2109.521983',
      '59295254.15813137',
      'BTC_USDT'
    ]
  ],
  id: null
} 
`

Please tell me how I'll differentiate which candle belongs to the 60-second interval candle

**Comment by john-whitebit** [comment]
Single WebSocket connection can handle only a single subscription to the candles_subscribe method. If you want to make multiple subscriptions for different time intervals (60 seconds, 120 seconds, and 300 seconds), you should establish separate WebSocket connections for each subscription.

By doing so, you can be sure that the candlestick updates received on each WebSocket connection correspond to the specific time interval you subscribed to, and you can easily differentiate between them.

**Comment by 5oni** [comment]
@john-whitebit Thanks for your suggestion It is definitely a workable solution but it will be hard to manage multiple connections. Adding candle interval or Id in response will make it easier to manage the data when subscribing to more candle intervals. It would be great if in any future update candle interval or Id could be added.

**Comment by john-whitebit** [comment]
Thank you for your patience and for sharing your suggestion with us. We appreciate your input and understand how adding candle interval or ID in the response can make managing multiple connections more efficient. We'll definitely consider this feature for future updates to improve the user experience. Your feedback is valuable, and we're always looking to make improvements based on our users' needs.
