### ISSUE TITLE
Subscribing to multiple transaction pairs

### ISSUE THREAD

**Issue by liuweiqin** [whitebit-exchange/api-docs#9]
const symbols = ["SOL", "TRB", 'NEAR']
ws.on('open', () => {
    symbols.forEach((item,index) => {
        let data = {
            "id": index+1,
            "method": "candles_subscribe",
            "params": [
                `${item}_PERP`,
                60,
            ],
        }
        ws.send(JSON.stringify(data))
    })
    ping()
})
Subscribing to multiple transaction pairs but only receiving the transaction pair message for the last subscription NEAR_PERP

**Comment by liuweiqin** [comment]
1

**Comment by liuweiqin** [comment]
c

**Comment by john-whitebit** [comment]
The issue you are encountering is due to the server only supporting a single `candles_subscribe` per connection. To subscribe to multiple transaction pairs (`SOL_PERP`, `TRB_PERP`, `NEAR_PERP`), you will need to create a new WebSocket connection for each subscription. Here's how you can modify your code to achieve this:

```javascript
const WebSocket = require('ws');

const symbols = ["SOL", "TRB", "NEAR"];
const createConnection = (symbol, index) => {
  const ws = new WebSocket('wss://api.whitebit.com/ws');

  ws.on('open', () => {
    let data = {
      "id": index + 1,
      "method": "candles_subscribe",
      "params": [`${symbol}_PERP`, 60],
    };
    ws.send(JSON.stringify(data));
    ping(ws);
  });

  ws.on('message', (message) => {
    console.log(`Received message for ${symbol}_PERP: `, message);
  });

  ws.on('error', (error) => {
    console.error(`WebSocket error for ${symbol}_PERP: `, error);
  });

  ws.on('close', () => {
    console.log(`WebSocket connection closed for ${symbol}_PERP`);
  });
};

const ping = (ws) => {
  setInterval(() => {
    ws.send(JSON.stringify({ method: 'ping' }));
  }, 30000); // Adjust the interval as needed
};

symbols.forEach((symbol, index) => {
  createConnection(symbol, index);
});
```

By creating separate WebSocket connections for each subscription, you can ensure that you receive messages for all the transaction pairs (`SOL_PERP`, `TRB_PERP`, `NEAR_PERP`).
